version: "3"

services:
  db:
    container_name: my_db
    image: postgres:alpine
    ports:
      - "${DB_PORT}:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  pg-data: